import { useState } from 'react';
import {
    useCreateTeamMemberMutation,
    useCreateUserMutation,
    useCheckUserExistsMutation,
    useFetchBusinessesQuery,
} from '../../../../store';
import SubmitButton from '../../../../utils/SubmitButton';
import Input from '../../../../utils/Input';
import Select from '../../../../utils/Select';

function generateStrongPassword(length = 12) {
    const charset = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()_-+=<>?';
    let password = '';
    const array = new Uint32Array(length);
    window.crypto.getRandomValues(array);
    for (let i = 0; i < length; i++) {
        password += charset[array[i] % charset.length];
    }
    return password;
}

export default function CreateTeamMemberForm({ token, showModal, setShowModal, setAlert }) {
    const [name, setName] = useState('');
    const [phone, setPhone] = useState('');
    const [email, setEmail] = useState('');
    const [role, setRole] = useState('EMPLOYEE');
    const [jobDuties, setJobDuties] = useState('');
    const [expertise, setExpertise] = useState('');

    const [createUser, { isLoading: isUserLoading }] = useCreateUserMutation();
    const [createTeamMember, { isLoading: isTeamMemberLoading }] = useCreateTeamMemberMutation();
    const [checkUserExists, { isLoading: isCheckingUser }] = useCheckUserExistsMutation();
    const { data: businesses } = useFetchBusinessesQuery(undefined, { skip: !token });

    const isSubmitting = isUserLoading || isTeamMemberLoading || isCheckingUser;

    const resetForm = () => {
        setName('');
        setPhone('');
        setEmail('');
        setRole('EMPLOYEE');
        setJobDuties('');
        setExpertise('');
    };

    const handleSubmit = async (e) => {
        e.preventDefault();

        if (!name || !email || !phone) {
            setAlert({ type: 'error', message: 'Please fill all required fields.' });
            return;
        }

        try {
            const checkResponse = await checkUserExists({ email }).unwrap();
            let userId = checkResponse?.id;

            if (!userId) {
                const password = generateStrongPassword();
                const userPayload = { name, email, phone, password, role };
                const newUser = await createUser(userPayload).unwrap();
                userId = newUser.id;
            }

            const businessId = businesses?.[0]?.id;
            if (!businessId) throw new Error('No business found for the current user.');

            await createTeamMember({
                business: businessId,
                employee: userId,
                job_duties: jobDuties,
                expertise,
            }).unwrap();

            setAlert({ type: 'success', message: 'Team member added successfully.' });
            resetForm();
            setShowModal(false);
        } catch (err) {
            console.error('Create team member error:', err);
            setAlert({
                type: 'error',
                message: 'Something went wrong while adding the team member. Please try again.',
            });
        }
    };

    return (
        <>
            {showModal && (
                <div className="modal d-block" tabIndex="-1" role="dialog">
                    <div className="modal-dialog" role="document">
                        <div className="modal-content">
                            <div className="modal-header">
                                <h5 className="modal-title fw-bold">Add New Member</h5>
                                <button
                                    type="button"
                                    className="btn-close"
                                    onClick={() => setShowModal(false)}
                                ></button>
                            </div>

                            <form onSubmit={handleSubmit}>
                                <div className="modal-body">
                                    <p className="p-2 bg-light rounded">
                                        Please note: Login credentials will be generated by our internal system. A
                                        confirmation link will be sent to the provided email. Team members will set
                                        their password via the "Forgot Password" option.
                                    </p>

                                    <div className="row">
                                        <div className="col-md-6">
                                            <Input
                                                id="name"
                                                label={'Name'}
                                                value={name}
                                                isRequired={true}
                                                onChange={setName}
                                                fieldClass={'form-control'}
                                            />
                                        </div>
                                        <div className="col-md-6">
                                            <Input
                                                id="email"
                                                label={'Email'}
                                                value={email}
                                                isRequired={true}
                                                onChange={setEmail}
                                                fieldClass={'form-control'}
                                            />
                                        </div>
                                        <div className="col-md-6">
                                            <Input
                                                type="tel"
                                                id="phone"
                                                label={'Phone'}
                                                value={phone}
                                                isRequired={true}
                                                onChange={setPhone}
                                                fieldClass={'form-control'}
                                            />
                                        </div>
                                        <div className="col-md-6">
                                            <Select
                                                id="role"
                                                label="Role"
                                                isRequired={true}
                                                onChange={setRole}
                                                options={[
                                                    { value: 'EMPLOYEE', label: 'Employee' },
                                                    { value: 'MANAGER', label: 'MANAGER' },
                                                ]}
                                            />
                                        </div>
                                        <div className="col-md-12 mb-3">
                                            <label className="form-label fw-bold">Job Duties</label>
                                            <textarea
                                                className="form-control"
                                                rows="3"
                                                value={jobDuties}
                                                onChange={(e) => setJobDuties(e.target.value)}
                                            ></textarea>
                                        </div>
                                        <div className="col-md-12">
                                            <Input
                                                id="expertise"
                                                label={'Expertise'}
                                                value={expertise}
                                                onChange={setExpertise}
                                                fieldClass={'form-control'}
                                            />
                                        </div>
                                    </div>
                                </div>

                                <div className="modal-footer">
                                    <button
                                        type="button"
                                        className="btn btn-sm btn-dark"
                                        onClick={() => setShowModal(false)}
                                        disabled={isSubmitting}
                                    >
                                        Cancel
                                    </button>
                                    <SubmitButton
                                        isLoading={isSubmitting}
                                        btnClass="btn btn-sm btn-success"
                                        btnName="Add Member"
                                    />
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            )}
            {showModal && <div className="modal-backdrop fade show"></div>}
        </>
    );
}
