# Generated by Django 3.2.25 on 2025-09-30 21:55

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='services_offered',
            field=taggit.managers.TaggableManager(blank=True, help_text='Add services offered by this business (comma-separated tags).', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('business', 'email'), name='unique_client_email_per_business'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('business', 'phone'), name='unique_client_phone_per_business'),
        ),
    ]
