# Generated by Django 3.2.25 on 2025-10-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('EMPLOYEE', 'Employee'), ('CLIENT', 'Client'), ('USER', 'User')], default='USER', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='servicequestionnaire',
            unique_together=set(),
        ),
    ]
