# Generated by Django 3.2.25 on 2025-10-28 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20251028_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='city',
        ),
        migrations.RemoveField(
            model_name='client',
            name='country',
        ),
        migrations.RemoveField(
            model_name='client',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='client',
            name='province_state',
        ),
        migrations.RemoveField(
            model_name='client',
            name='street_address',
        ),
    ]
