# Generated by Django 3.2.25 on 2025-10-11 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20251011_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(help_text='Name of the service this questionnaire is for', max_length=100)),
                ('additional_questions_form', models.JSONField(blank=True, help_text='Stores the dynamic questionnaire structure for the service', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_questionnaires', to='core.business')),
            ],
            options={
                'ordering': ['business', 'service_name'],
                'unique_together': {('business', 'service_name')},
            },
        ),
    ]
