# Generated by Django 3.2.25 on 2025-10-06 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('business', 'user')},
        ),
    ]
