# Generated by Django 3.2.25 on 2025-10-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20251002_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='phone',
            field=models.CharField(default=5875001189, max_length=20),
            preserve_default=False,
        ),
    ]
