# Generated by Django 3.2.25 on 2025-10-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_servicequestionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='filled_questionnaire',
            field=models.JSONField(blank=True, help_text="Stores client responses for this service's questionnaire in JSON format", null=True),
        ),
    ]
