# Generated by Django 3.2.25 on 2025-10-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_teammember_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
