# Generated by Django 3.2.25 on 2025-11-01 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_invoice_payout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='quote',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='core.service'),
        ),
    ]
