# Generated by Django 3.2.25 on 2025-10-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='signed_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='terms_conditions',
            field=models.TextField(default='dsds'),
            preserve_default=False,
        ),
    ]
