# Generated by Django 3.2.25 on 2025-10-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20251007_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
