# Generated by Django 3.2.25 on 2025-10-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20251017_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankinginformation',
            name='payment_method_type',
            field=models.CharField(choices=[('BANK_ACCOUNT', 'Bank Account'), ('CARD', 'Credit/Debit Card')], default='CARD', max_length=20),
        ),
    ]
