# Generated by Django 3.2.25 on 2025-11-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20251101_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='business',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
