# Generated by Django 3.2.25 on 2025-10-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_service_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='currency',
            field=models.CharField(choices=[('CAD', 'CAD'), ('USD', 'USD')], default='CAD', max_length=3),
        ),
    ]
