# Generated by Django 3.2.25 on 2025-10-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_quote_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('SIGNED', 'Signed'), ('DECLINED', 'Declined')], default='DRAFT', max_length=20),
        ),
    ]
