# Generated by Django 3.2.25 on 2025-11-02 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20251102_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='stripe_invoice_id',
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='core.bankinginformation'),
        ),
        migrations.AddField(
            model_name='payout',
            name='stripe_transfer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payout',
            name='banking_information',
            field=models.ForeignKey(blank=True, help_text='Business banking or connected account details used for this payout.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='core.bankinginformation'),
        ),
    ]
