# Generated by Django 3.2.25 on 2025-10-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_service_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='city',
            field=models.CharField(default='Calgary', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='country',
            field=models.CharField(default='CA', max_length=2),
        ),
        migrations.AddField(
            model_name='service',
            name='postal_code',
            field=models.CharField(default='pp', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='province_state',
            field=models.CharField(default='oo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='street_address',
            field=models.CharField(default='7687', max_length=255),
            preserve_default=False,
        ),
    ]
