# Generated by Django 3.2.25 on 2025-10-26 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_bankinginformation_payment_method_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankinginformation',
            name='is_default',
        ),
    ]
