# Generated by Django 3.2.25 on 2025-10-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_quote_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='signed_by',
        ),
        migrations.AlterField(
            model_name='quote',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='media/signatures/'),
        ),
    ]
