# Generated by Django 3.2.25 on 2025-11-02 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20251102_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankinginformation',
            name='stripe_bank_account_id',
        ),
        migrations.AlterField(
            model_name='payout',
            name='banking_information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='core.bankinginformation'),
        ),
    ]
