# Generated by Django 3.2.25 on 2025-10-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_bankinginformation_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankinginformation',
            name='account_holder_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('company', 'Company')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bankinginformation',
            name='country',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='bankinginformation',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bankinginformation',
            name='stripe_bank_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bankinginformation',
            name='stripe_connected_account_id',
            field=models.CharField(blank=True, help_text='The Stripe connected account this bank account belongs to.', max_length=255, null=True),
        ),
    ]
