# Generated by Django 3.2.25 on 2025-11-11 23:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20251102_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='banking_information',
        ),
        migrations.AddField(
            model_name='business',
            name='owner_dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='owner_email',
            field=models.EmailField(default='test@email.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='owner_first_name',
            field=models.CharField(default='first name', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='owner_last_name',
            field=models.CharField(default='last name', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='owner_percent_ownership',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Percent ownership of the business owner (0-100).', max_digits=5),
        ),
        migrations.AddField(
            model_name='business',
            name='representative_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='representative_email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='representative_first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='representative_last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='representative_percent_ownership',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Percent ownership of the representative (0-100).', max_digits=5),
        ),
        migrations.AddField(
            model_name='business',
            name='slug',
            field=models.CharField(default='zs-projects', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='support_phone',
            field=models.CharField(default='+15875001189', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='website',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
