# Generated by Django 3.2.25 on 2025-11-12 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20251111_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='representative_percent_ownership',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percent ownership of the representative (0-100).', max_digits=5),
        ),
    ]
