# Generated by Django 3.2.25 on 2025-11-12 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_business_representative_percent_ownership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='representative_dob',
        ),
        migrations.RemoveField(
            model_name='business',
            name='representative_email',
        ),
        migrations.RemoveField(
            model_name='business',
            name='representative_first_name',
        ),
        migrations.RemoveField(
            model_name='business',
            name='representative_last_name',
        ),
        migrations.RemoveField(
            model_name='business',
            name='representative_percent_ownership',
        ),
    ]
