# Generated by Django 3.2.25 on 2025-11-12 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20251112_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='owner_phone',
            field=models.CharField(default='+15875001189', max_length=20),
            preserve_default=False,
        ),
    ]
