# Generated by Django 3.2.25 on 2025-11-13 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_business_owner_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankinginformation',
            name='routing_number',
        ),
        migrations.RemoveField(
            model_name='bankinginformation',
            name='transit_number',
        ),
        migrations.RemoveField(
            model_name='business',
            name='owner_dob',
        ),
        migrations.RemoveField(
            model_name='business',
            name='owner_email',
        ),
        migrations.RemoveField(
            model_name='business',
            name='owner_first_name',
        ),
        migrations.RemoveField(
            model_name='business',
            name='owner_last_name',
        ),
        migrations.RemoveField(
            model_name='business',
            name='owner_percent_ownership',
        ),
        migrations.RemoveField(
            model_name='business',
            name='owner_phone',
        ),
        migrations.RemoveField(
            model_name='business',
            name='support_phone',
        ),
    ]
