# Generated by Django 3.2.25 on 2025-11-13 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20251113_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankinginformation',
            name='auto_payments',
            field=models.BooleanField(default=False),
        ),
    ]
