# Generated by Django 3.2.25 on 2025-11-13 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_bankinginformation_auto_payments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payout',
            name='stripe_balance_transaction_id',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='stripe_payout_id',
        ),
        migrations.AddField(
            model_name='payout',
            name='is_refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payout',
            name='refund_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='refunded_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount refunded from this payout (if partial refund).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, help_text='ID of the Stripe PaymentIntent used for the original charge.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='stripe_refund_id',
            field=models.CharField(blank=True, help_text='ID of the Stripe Refund if this payout was refunded.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='stripe_reversal_id',
            field=models.CharField(blank=True, help_text='ID of the Transfer Reversal created automatically by Stripe during refund.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payout',
            name='stripe_transfer_id',
            field=models.CharField(blank=True, help_text='ID of the Stripe Transfer to the connected account.', max_length=255, null=True),
        ),
    ]
