# Generated by Django 3.2.25 on 2025-11-13 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20251113_0321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='stripe_payment_intent_id',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='stripe_reversal_id',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='stripe_transfer_id',
        ),
        migrations.AlterField(
            model_name='payout',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
