# Generated by Django 3.2.25 on 2025-11-15 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20251113_0404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payout',
            name='initiated_at',
        ),
        migrations.AddField(
            model_name='service',
            name='auto_generate_invoices',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='auto_generate_quote',
            field=models.BooleanField(default=False),
        ),
    ]
